# Generated by Django 4.0.3 on 2022-04-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='date',
        ),
    ]
