# Generated by Django 4.0.3 on 2022-04-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_rate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
