# Generated by Django 4.0.3 on 2022-04-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_rate_content_alter_rate_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
