# Generated by Django 4.0.3 on 2022-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_rate_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='average_rating',
        ),
    ]
